### ISSUE TITLE
Hanging issue with get dominfo during VM shutdown

### ISSUE THREAD

**Issue by donghunkim-zacky** [inovex/prometheus-libvirt-exporter#58] opened 2024-12-19 04:23 UTC
We're experiencing an issue with the inovex libvirt exporter hanging during VM shutdown, particularly for resource-intensive VMs (e.g., multiple GPUs, high memory).

**Issue:**
- VM shutdown for large instances can take 1-2 minutes.
- The exporter, collecting data every minute, hangs on get dominfo during shutdown.
- This causes gaps in our monitoring data.

**Question:**
- Can we implement a non-blocking or timeout mechanism for read-only operations like get dominfo? This would allow continued monitoring even during VM shutdowns.
- The lock is specific to a particular VM, but it's causing the entire host monitoring information to hang. Is there a way to implement a "nowait" option or similar mechanism to prevent this global impact? 

Any insights or suggestions are appreciated.

**Comment by frittentheke** [comment] 2024-12-19 11:59
This is somewhat of a duplicate of #53, which reports the same issue for migrations.
The issue is known and there attempt to fix this or make the exporter more tolerant in this regard will me made.
Ideas and PRs are always welcome though!

**Closed by frittentheke** 2024-12-19 11:59 UTC
